plugins {
  id 'java'
}

dependencies {
  implementation libraries.base
  implementation libraries.apacheBase
  implementation project(':luwrain-base')
  implementation project(':luwrain')
  //implementation project(':luwrain-io')
  annotationProcessor libraries.autoService
  annotationProcessor project(':luwrain-base')
  implementation 'com.squareup.okhttp3:okhttp:4.12.0'
  testImplementation libraries.junit
}

tasks.named('test') {
  useJUnitPlatform()
}
